name: nixos-tests

on: push
jobs:
  nixos-test:
    runs-on: actuated
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
      - name: NixOS test
        run: |
          sudo chmod o+rw /dev/kvm
          nix build -L .#checks.x86_64-linux.postgres
